#! /usr/bin/perl -w

use strict;
use warnings;
use feature 'say';
use File::Copy;
use Archive::Extract;
use XML::LibXML;
use File::Slurp;
use File::Path qw(remove_tree);

# After unzip : opf file (unique) is in OEBPS directory

die "Please feed me with epub files !"
  unless ( $ARGV[0] =~ /\.epub$/i );

my $filename = $ARGV[0];
$filename =~ s/\.epub$/$'/i;

copy( $ARGV[0], $filename . '.zip' );

my $epub = Archive::Extract->new( archive => $filename . '.zip' );

mkdir 'epub'
  or die "Unable to make dir 'epub' : $!";
chdir 'epub'
  or die "Unable to change to dir 'epub' : $!";

$epub->extract
  or die "Unable to extract $ARGV[0] : $!";

chdir 'OEBPS'
  or die "Unable to change to OEBPS : $!";

my $parser = XML::LibXML->new();
my $doc    = $parser->parse_file( glob('*.opf') );

my $xpc = XML::LibXML::XPathContext->new($doc);
$xpc->registerNs( opf => 'http://www.idpf.org/2007/opf' );

my @htmlfiles;

foreach my $item ( $xpc->findnodes('//opf:item') ) {
  if ( $item->findvalue('@media-type') eq 'application/xhtml+xml' ) {
    push( @htmlfiles, $item->findvalue('@href') );
  }
}


##### I know I shouldn't use regexp on HTML blah blah blah
##### it does work and it is *much much* faster than what I tested otherwise

my $header = q{
<html>
 <!-- This ugly file is automatically generated by epub2html.pl -->
 <!-- It is intend to produce a simple HTML file out of an EPUB file -->
 <!-- Basically to be read in w3m or other text-based web-browsers -->
 <!-- (which is why I don't care about img) -->
 <!-- https://github.com/SebDeclercq/scriptsOfMine/blob/master/epub2html.pl -->
<body>
};

write_file( '../../' . $filename . '.html',
	    { binmode => ':utf8', append => 1 }, $header );

for (@htmlfiles) {
  my $file = read_file($_, {binmode => ':utf8'});
  $file =~ s/.*<body>//si;
  $file =~ s/<\/body> *<\/html>//si;
  write_file( '../../' . $filename . '.html',
	      { binmode => ':utf8', append => 1 }, $file );
}

my $footer = q{
  </body>
</html>
};

write_file( '../../' . $filename . '.html',
	    { binmode => ':utf8', append => 1 }, $footer );

chdir '../..';
remove_tree 'epub'
  or die "Unable to delete epub directory : $!";
